[build]
  command = "pnpm install && pnpm build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["resend", "@react-email/render", "html-to-text", "js-beautify", "prettier", "deepmerge", "config-chain", "editorconfig", "dom-serializer", "@selderee/plugin-htmlparser2", "selderee"]

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"  # forcera pnpm si pnpm-lock.yaml est détecté
